title: Microservicio de pagos
description: Documentacion del microservicio que gestiona los pagos de "SocioUnido"
theme: just-the-docs

url: "https://trabajoprofesional-aggz.github.io"

baseurl: "/microservicio-pagos"
